// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UcRRMLgIP-q0OLLJnpoMRBg71NE8ipI',
    appId: '1:364694556273:web:8ba84035bfa3f706a255d0',
    messagingSenderId: '364694556273',
    projectId: 'flutterauthen-5b041',
    authDomain: 'flutterauthen-5b041.firebaseapp.com',
    storageBucket: 'flutterauthen-5b041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJx9qcVk8IJGBilcbRnUGMxV4HdpV4DoQ',
    appId: '1:364694556273:android:6bbb78bb8a15c88ba255d0',
    messagingSenderId: '364694556273',
    projectId: 'flutterauthen-5b041',
    storageBucket: 'flutterauthen-5b041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxvlYamKWWitq7J-6rrRJ-vXzM2RzBFk',
    appId: '1:364694556273:ios:40f0521a4a58f061a255d0',
    messagingSenderId: '364694556273',
    projectId: 'flutterauthen-5b041',
    storageBucket: 'flutterauthen-5b041.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBxvlYamKWWitq7J-6rrRJ-vXzM2RzBFk',
    appId: '1:364694556273:ios:5fc9a7795fef74b2a255d0',
    messagingSenderId: '364694556273',
    projectId: 'flutterauthen-5b041',
    storageBucket: 'flutterauthen-5b041.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
